ucontroller
  ucontroller.alu:I_ALU
  ucontroller.cpu:I_CPU
  ucontroller.dma:I_DMA
    ucontroller.dma:I_DMA.dma_arbiter:I_DMA_ARBITER
    ucontroller.dma:I_DMA.dma_rx:I_DMA_RX
    ucontroller.dma:I_DMA.dma_tx:I_DMA_TX
  ucontroller.ram:I_RAM
    ucontroller.ram:I_RAM.gp_ram:I_GP_RAM
    ucontroller.ram:I_RAM.regs_ram:I_REGS_RAM
      ucontroller.ram:I_RAM.regs_ram:I_REGS_RAM.bin2bcd:I_BIN2BCD
  ucontroller.ram_arbiter:I_RAM_ARBITER
  ucontroller.uart:I_UART
    ucontroller.uart:I_UART.fifo_wrapper:I_FIFO
    ucontroller.uart:I_UART.sreg:I_SREG
    ucontroller.uart:I_UART.uart_rx:I_UART_RX
    ucontroller.uart:I_UART.uart_tx:I_UART_TX
