// Hierarchy generated by `verilog-ext'

// * ucontroller
// ** alu
// ** cpu
// ** dma
// *** dma_arbiter
// *** dma_rx
// *** dma_tx
// ** ram
// *** gp_ram
// *** regs_ram
// **** bin2bcd
// ** ram_arbiter
// ** uart
// *** fifo_wrapper
// *** sreg
// *** uart_rx
// *** uart_tx


// * Not found module references
// ** fifo_generator_0


// * Buffer local variables
// Local Variables:
// eval: (verilog-ext-hierarchy-outshine-nav-mode)
// End:
