#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data
	      (("ieee" :file "vhdl/files/common/indent_misc.vhd" :line 7)
	       (:desc "library ieee, work;" :col 8)
	       ("work" :file "vhdl/files/common/indent_misc.vhd" :line 7)
	       (:desc "library ieee, work;" :col 14)
	       ("ieee" :file "vhdl/files/common/indent_misc.vhd" :line 9)
	       (:desc "use ieee.std_logic_1164.all;" :col 4)
	       ("std_logic_1164" :file "vhdl/files/common/indent_misc.vhd" :line 9)
	       (:desc "use ieee.std_logic_1164.all;" :col 9)
	       ("foo" :file "vhdl/files/common/indent_misc.vhd" :line 14)
	       (:desc "entity foo is" :col 7)
	       ("foo" :file "vhdl/files/common/indent_misc.vhd" :line 15)
	       (:desc "end entity foo;" :col 11)
	       ("indent" :file "vhdl/files/common/indent_misc.vhd" :line 21)
	       (:desc "architecture indent of indent_test is" :col 13)
	       ("indent_test" :file "vhdl/files/common/indent_misc.vhd" :line 21)
	       (:desc "architecture indent of indent_test is" :col 23)
	       ("var" :file "vhdl/files/common/indent_misc.vhd" :line 27)
	       (:desc "case var is" :col 5)
	       ("A" :file "vhdl/files/common/indent_misc.vhd" :line 28)
	       (:desc "when A =>" :col 5)
	       ("out" :file "vhdl/files/common/indent_misc.vhd" :line 29)
	       (:desc "out <= in;" :col 0)
	       ("in" :file "vhdl/files/common/indent_misc.vhd" :line 29)
	       (:desc "out <= in;" :col 7)
	       ("B" :file "vhdl/files/common/indent_misc.vhd" :line 30)
	       (:desc "when B =>" :col 5)
	       ("out" :file "vhdl/files/common/indent_misc.vhd" :line 31)
	       (:desc "out <= in;" :col 0)
	       ("in" :file "vhdl/files/common/indent_misc.vhd" :line 31)
	       (:desc "out <= in;" :col 7)
	       ("C" :file "vhdl/files/common/indent_misc.vhd" :line 32)
	       (:desc "when C =>" :col 5)
	       ("out" :file "vhdl/files/common/indent_misc.vhd" :line 33)
	       (:desc "out <= in;" :col 0)
	       ("in" :file "vhdl/files/common/indent_misc.vhd" :line 33)
	       (:desc "out <= in;" :col 7)
	       ("out" :file "vhdl/files/common/indent_misc.vhd" :line 35)
	       (:desc "out <= in;" :col 0)
	       ("in" :file "vhdl/files/common/indent_misc.vhd" :line 35)
	       (:desc "out <= in;" :col 7)
	       ("indent" :file "vhdl/files/common/indent_misc.vhd" :line 39)
	       (:desc "end architecture indent;" :col 17)
	       ("foo" :file "vhdl/files/common/indent_misc.vhd" :line 43)
	       (:desc "package body foo is" :col 13)
	       ("ARRAY_CONSTANT" :file "vhdl/files/common/indent_misc.vhd" :line 44)
	       (:desc "constant ARRAY_CONSTANT : array_type :=" :col 9)
	       ("array_type" :file "vhdl/files/common/indent_misc.vhd" :line 44)
	       (:desc "constant ARRAY_CONSTANT : array_type :=" :col 26)
	       ("VALUE_0" :file "vhdl/files/common/indent_misc.vhd" :line 46)
	       (:desc "VALUE_0," :col 0)
	       ("VALUE_1" :file "vhdl/files/common/indent_misc.vhd" :line 47)
	       (:desc "VALUE_1," :col 0)
	       ("VALUE_2" :file "vhdl/files/common/indent_misc.vhd" :line 48)
	       (:desc "VALUE_2," :col 0)
	       ("VALUE_3" :file "vhdl/files/common/indent_misc.vhd" :line 49)
	       (:desc "VALUE_3," :col 0)
	       ("VALUE_4" :file "vhdl/files/common/indent_misc.vhd" :line 50)
	       (:desc "VALUE_4" :col 0)
	       ("foo" :file "vhdl/files/common/indent_misc.vhd" :line 52)
	       (:desc "end package body foo;" :col 17)
	       ("foo" :file "vhdl/files/common/indent_misc.vhd" :line 56)
	       (:desc "package body foo is" :col 13)
	       ("test_multiline_expression" :file "vhdl/files/common/indent_misc.vhd" :line 57)
	       (:desc "procedure test_multiline_expression is" :col 10)
	       ("signal_out" :file "vhdl/files/common/indent_misc.vhd" :line 59)
	       (:desc "signal_out <= signal_in1 and" :col 0)
	       ("signal_in1" :file "vhdl/files/common/indent_misc.vhd" :line 59)
	       (:desc "signal_out <= signal_in1 and" :col 14)
	       ("signal_in2" :file "vhdl/files/common/indent_misc.vhd" :line 60)
	       (:desc "signal_in2 and" :col 0)
	       ("signal_in3" :file "vhdl/files/common/indent_misc.vhd" :line 61)
	       (:desc "signal_in3 and" :col 0)
	       ("signal_in4" :file "vhdl/files/common/indent_misc.vhd" :line 62)
	       (:desc "signal_in4;" :col 0)
	       ("test_multiline_expression" :file "vhdl/files/common/indent_misc.vhd" :line 63)
	       (:desc "end procedure test_multiline_expression;" :col 14)
	       ("foo" :file "vhdl/files/common/indent_misc.vhd" :line 64)
	       (:desc "end package body foo;" :col 17)))
